//Mock data-------------------------------------
const config = {
  "interval": 1,//1,2,3,4...
  "pattern": [
/*001*/"rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*002*/"__rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*003*/"____rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*004*/"______rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*005*/"________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*006*/"__________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*007*/"____________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*008*/"______________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*009*/"________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*010*/"__________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*011*/"____________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*012*/"______________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*013*/"rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*014*/"__rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*015*/"____rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*016*/"______rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*017*/"________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*018*/"__________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*019*/"____________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*020*/"______________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*021*/"________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*022*/"__________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*023*/"____________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*024*/"______________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*025*/"rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*026*/"__rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*027*/"____rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*028*/"______rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*029*/"________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*030*/"__________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*031*/"____________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*032*/"______________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*033*/"________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*034*/"__________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*035*/"____________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*036*/"______________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*037*/"rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*038*/"__rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*039*/"____rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*040*/"______rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*041*/"________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*042*/"__________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*043*/"____________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*044*/"______________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww________|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*045*/"________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP______________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww______|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*046*/"__________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*047*/"____________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP__________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww__|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
/*048*/"______________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww|rrrrrrrrrrroooooooooooooyyyyyyyyyyyyyylllllllllllllllggggggggggggggggsssssssssssssssaaaaaaaaaaaaaaaSSSSSSSSSSSSSSSbbbbbbbbbbbbbbvvvvvvvvvvvvvvvppppppppppppppppPPPPPPPPPPPPPPP____________________________rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwww_rrrrrrrr_wwwwwwww|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww____|rrrrrrrrrrrrrrrrr__ggggggggggggggggggggg__wwwwwwww__rrrrrrrr__wwwwwwww__rrrrrrrr__wwwwwww__rrrrrrr",
  ],
  "colors": {
    'r': {r: 1, g: 0, b: 0},//red rgb(255,0,0)
    //------------------------------------
    'o': {r: 1, g: .5, b: 0},//orange rgb(255,128,0)
    //------------------------------------
    'y': {r: 1, g: 1, b: 0},//yellow rgb(255,255,0)
    //------------------------------------
    'l': {r: .5, g: 1, b: 0},//lime rgb(128,255,0)
    //------------------------------------
    'g': {r: 0, g: 1, b: 0},//green rgb(0,255,0)
    //------------------------------------
    's': {r: 0, g: 1, b: .5},//spring green rgb(0,255,128)
    //------------------------------------
    'a': {r: 0, g: 1, b: 1},//aqua rgb(0,255,255)
    //------------------------------------
    'S': {r: 0, g: .5, b: 1},//sky blue rgb(0,128,255)
    //------------------------------------
    'b': {r: 0, g: 0, b: 1},//blue rgb(0,0,255)
    //------------------------------------
    'v': {r: .5, g: 0, b: 1},//violet rgb(128,0,255)
    //------------------------------------
    'p': {r: 1, g: 0, b: 1},//purple rgb(255,0,255)
    //------------------------------------
    'P': {r: 1, g: 0, b: .5},//pink rgb(255,0,128)
    //------------------------------------
    'w': {r: 1, g: 1, b: 1},//white
    //------------------------------------
    '_': {r: 0, g: 0, b: 0}//black
  }
}
//----------------------------------------------
//Constants
const RAYS_COUNT = 48;
const INTERVAL = config.interval;
const COLORS = config.colors;

//ThreeJS components
const loader = new THREE.ObjectLoader();
const scene = new THREE.Scene();
const gridHelper = new THREE.GridHelper(null, null, 'red', 'green');//turn off later

const camera = new THREE.PerspectiveCamera(
  45,
  window.innerWidth / window.innerHeight,
  0.1,
  1000);
camera.position.set(130, 100, 110);//start camera position
camera.lookAt(0,0,0);

const renderer = new THREE.WebGLRenderer({
  alpha: false,
  antialias: false
});
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

const controls = new THREE.OrbitControls(camera);

const ambientLight  = new THREE.AmbientLight('#fff');
// const hemiLight     = new THREE.HemisphereLight('#FAFAFA', '#FAFAFA', 0);
// hemiLight.position.set( 0, 1, 0 );
// const light         = new THREE.PointLight('#FAFAFA', 1, 100);
// light.position.set( 2.5, 1.5, 2 );


for(let i = 0; i < RAYS_COUNT; i++) {
  loader.load("src/3d/ray03.json", function( group ) {
    mesh = group.children[0];
    mesh.rotation.y = 360 / 57.4 / RAYS_COUNT * i;
    scene.add(mesh);
    scene.add(gridHelper);
    scene.add(ambientLight);
    // scene.add(hemiLight);
    // scene.add(light);
  });
  if(i === RAYS_COUNT - 1){
    console.log(scene);
  }
}

let step = 0;

function animate(){
  requestAnimationFrame(animate);

  function animateOneRay(i){
    const elements = scene.children[i].children;
    const elsCount = elements.length;
    // console.log(elsCount);

    
    let colorsSequence = config.pattern[i].replace('|', '').split('');
    colorsSequence.unshift(...new Array(elsCount).fill('_'));
    colorsSequence.push(...new Array(elsCount).fill('_'));
    colorsSequence = colorsSequence.map(el => COLORS[el]);
    // console.log(colorsSequence);
    let curColorsStep = [];


    if(step % INTERVAL === 0){
      curColorsStep = colorsSequence.slice(step / INTERVAL , step / INTERVAL  + elsCount);
      assignColors(i, elements, curColorsStep);
    };

  }

  function assignColors(ray, elements, colors){
    for(let i = 0; i < elements.length; i++){
      scene.children[ray].children[i].material.color = colors[i];
    }
  }
  
  for(let i = 0; i < RAYS_COUNT; i++) {
    animateOneRay(i);
  }

  step++;

  controls.update();
  renderer.render( scene, camera );
}

setTimeout(animate, 1000);
